(async page => {
  const qa = __AI_EDITOR_QA__, checks = [], errors = [];
  const check = (value, label) => { if (!value) throw new Error(label); checks.push(label); };
  page.on('pageerror', error => errors.push(error.message));
  const control = async body => (await (body ? page.request.post(qa.origin + '/api/qa/proposal-control', { data: body }) : page.request.get(qa.origin + '/api/qa/proposal-control'))).json();
  const signIn = async account => {
    const result = await page.evaluate(async ({ account, module }) => { window.aiQaAuth = await import(module); const client = await window.aiQaAuth.sb(); return (await client.auth.signInWithPassword({ email: account.email, password: account.password })).error?.message; }, { account, module: qa.authModule });
    check(!result, 'actual local account signs in'); await page.waitForFunction(owner => window.aiQaAuth.getUser()?.id === owner, account.owner);
  };
  await signIn(qa.accounts[0]);
  const editor = page.locator('dialog.course-editor');
  const openEditor = async () => {
    await page.goto(qa.origin + '/?experience=workspace&filter=mine');
    await page.getByRole('link', { name: /^Review course\s*:\s*AI Editor Photography QA/ }).click();
    await page.getByRole('button', { name: 'Make changes', exact: true }).click();
    await editor.getByRole('button', { name: 'Ask AI to improve this', exact: true }).waitFor();
  };
  const selectConcept = async () => { const option = editor.getByRole('option', { name: /Photography lesson 1 — Concept 1/ }); await editor.locator('[data-editor-target]').selectOption(await option.getAttribute('value')); };
  const ask = () => editor.getByRole('button', { name: 'Ask AI to improve this', exact: true }).click();
  const feedback = () => editor.getByRole('textbox', { name: 'What should change?', exact: true });
  const generate = () => editor.getByRole('button', { name: 'Generate proposal', exact: true }).click();
  const waitReady = async () => { await editor.getByRole('heading', { name: 'Your suggestion is ready', exact: true }).waitFor({ timeout: 15000 }); };
  await openEditor(); await selectConcept(); check((await control()).calls === 0, 'opening/selecting does not run AI');
  await editor.getByRole('textbox', { name: 'Title', exact: true }).first().fill('My retained manual opening'); await ask();
  check(await editor.getByText('Provider charges apply', { exact: false }).isVisible(), 'cost and no-auto-retry disclosure precedes generation');
  await feedback().fill('short'); await generate(); await editor.getByRole('alert').waitFor();
  check((await control()).calls === 0 && await feedback().inputValue() === 'short', 'short feedback is retained without calling AI');
  await feedback().fill('🙂'.repeat(2001)); await generate();
  check((await feedback().inputValue()).length === 4002 && (await control()).calls === 0, 'Unicode limit rejects without truncating or calling AI');
  await feedback().fill('Keep my current manual edit and clarify the explanation.');
  check(await editor.getByRole('alert').count() === 0, 'correcting feedback clears the resolved validation warning');
  for (const width of [1440, 390, 320]) {
    await page.setViewportSize({ width, height: 1000 });
    check(await editor.evaluate(el => el.scrollWidth <= el.clientWidth), `${width}px AI input has no horizontal overflow`);
    await editor.screenshot({ path: `output/playwright/ai-editor-input-${width}.png` });
  }
  await control({ delay: true }); let loseStart = true, lostReply;
  await page.route('**/api/courses/proposal*', async route => {
    if (route.request().method() === 'POST' && route.request().postDataJSON()?.action === 'start' && loseStart) { loseStart = false; const reply = await route.fetch(); lostReply = { status: reply.status(), body: await reply.json() }; return route.abort('failed'); }
    return route.continue();
  });
  await generate(); await editor.getByRole('button', { name: 'Check the same AI request', exact: true }).waitFor();
  await page.waitForFunction(() => document.querySelector('[data-editor-ai-action="check"]')?.disabled === false && document.querySelector('dialog [role="alert"]')?.textContent.includes('could not be confirmed'));
  for (let attempt = 0; attempt < 100 && (await control()).calls === 0; attempt++) await page.waitForTimeout(100);
  const afterStart = await control();
  if (afterStart.calls !== 1 || afterStart.lastManualTitle !== 'My retained manual opening') throw new Error('Unexpected start result: ' + JSON.stringify({ afterStart, lostReply }));
  check(true, 'one request includes the current manual draft');
  await editor.getByRole('button', { name: 'Check the same AI request', exact: true }).click();
  await editor.getByRole('heading', { name: 'Preparing your suggestion', exact: true }).waitFor();
  check((await control()).calls === 1, 'lost reply checks the same generation rather than charging again');
  await editor.getByRole('button', { name: 'Cancel request', exact: true }).focus();
  await page.waitForResponse(response => response.url().includes('/api/courses/proposal?') && response.request().method() === 'GET');
  await page.waitForTimeout(100);
  check(await editor.getByRole('button', { name: 'Cancel request', exact: true }).evaluate(el => el === document.activeElement), 'background status refresh preserves keyboard focus');
  await editor.screenshot({ path: 'output/playwright/ai-editor-running-320.png' });
  await editor.getByRole('button', { name: 'Close course editor' }).click();
  check(await editor.count() === 0, 'persisted request/draft can leave without a false loss warning');
  await openEditor(); await editor.getByRole('button', { name: 'Continue saved AI request', exact: true }).click();
  await editor.getByRole('heading', { name: 'Preparing your suggestion', exact: true }).waitFor();
  check((await control()).calls === 1, 'fresh page/account copy recovers request without regeneration');
  await control({ release: true, delay: false }); await editor.getByRole('button', { name: 'Check this request', exact: true }).click(); await waitReady();
  check((await control()).title !== 'AI revised opening for review', 'ready AI output has not changed saved course');
  check(await editor.getByText('80 input / 40 output', { exact: false }).isVisible(), 'actual returned token usage is visible');
  await editor.getByRole('button', { name: 'Review AI suggestion', exact: true }).click();
  await editor.getByRole('heading', { name: 'Review your change', exact: true }).waitFor();
  check(await editor.getByText('AI revised opening for review', { exact: true }).isVisible(), 'comparison shows validated AI replacement');
  await editor.getByRole('button', { name: 'Keep editing', exact: true }).click();
  check(await editor.getByRole('textbox', { name: 'Title', exact: true }).first().inputValue() === 'My retained manual opening', 'back from AI comparison restores the manual draft');
  await ask(); await editor.getByRole('button', { name: 'Review AI suggestion', exact: true }).click();
  for (const width of [1440, 320]) {
    await page.setViewportSize({ width, height: 1000 });
    check(await editor.evaluate(el => el.scrollWidth <= el.clientWidth), `${width}px AI comparison has no horizontal overflow`);
    await editor.screenshot({ path: `output/playwright/ai-editor-comparison-${width}.png` });
  }
  await editor.getByRole('button', { name: 'Replace this item', exact: true }).click(); await editor.getByRole('heading', { name: 'Change saved', exact: true }).waitFor();
  check((await control()).title === 'AI revised opening for review' && (await control()).status === 'applied', 'explicit replace updates account content and consumes proposal');
  await editor.getByRole('link', { name: 'Open updated lesson', exact: true }).click();
  await page.getByText('AI revised opening for review', { exact: true }).waitFor();
  check(true, 'actual learner opens accepted AI content');
  await openEditor(); check(await editor.getByRole('button', { name: 'Continue saved AI request', exact: true }).count() === 0, 'applied suggestion is not offered again');
  await selectConcept(); await ask(); await feedback().fill('Prepare another variation for this selected explanation.'); await control({ delay: true }); await generate();
  await editor.getByRole('heading', { name: 'Preparing your suggestion', exact: true }).waitFor({ timeout: 15000 });
  await editor.getByRole('button', { name: 'Cancel request', exact: true }).click(); await editor.getByRole('heading', { name: 'Request cancelled', exact: true }).waitFor();
  await control({ release: true, delay: false });
  check(await editor.getByRole('button', { name: 'Review AI suggestion', exact: true }).count() === 0, 'cancelled suggestion cannot be reviewed or applied');
  await editor.getByRole('button', { name: 'Discard suggestion', exact: true }).click();
  await control({ outcome: 'invalid' }); await feedback().fill('Try a new explanation but retain the current lesson goals.'); await generate();
  await editor.getByRole('heading', { name: 'Suggestion could not be completed', exact: true }).waitFor({ timeout: 15000 });
  check(await editor.getByRole('button', { name: 'Generate proposal', exact: true }).isVisible() && await editor.getByText('80 input / 40 output', { exact: false }).isVisible(), 'invalid output retains feedback, reports usage and offers only explicit retry');
  const failedCalls = (await control()).calls;
  await editor.getByRole('button', { name: 'Back to manual editing', exact: true }).click(); await ask();
  check((await control()).calls === failedCalls, 'reopening a failed proposal does not retry');
  await editor.getByRole('button', { name: 'Discard suggestion', exact: true }).click();
  await control({ outcome: 'ok' }); await feedback().fill('Make one further focused improvement to this explanation.'); await generate(); await waitReady();
  await control({ edit: true }); await editor.getByRole('button', { name: 'Review AI suggestion', exact: true }).click();
  await editor.getByRole('button', { name: 'Load latest and keep my text', exact: true }).click();
  await ask(); await editor.getByRole('button', { name: 'Review AI suggestion', exact: true }).click();
  await editor.getByRole('heading', { name: 'Review your change', exact: true }).waitFor();
  check(await editor.getByText('Newer accepted manual opening', { exact: true }).isVisible(), 'stale proposal compares against freshly loaded saved content');
  await editor.getByRole('button', { name: 'Keep editing', exact: true }).click(); await ask();
  await editor.getByRole('button', { name: 'Discard suggestion', exact: true }).click();
  await feedback().waitFor();
  await page.evaluate(() => document.documentElement.setAttribute('data-theme', 'dark'));
  check(await editor.getByRole('alert').count() === 0, 'discarding stale suggestion clears its obsolete warning');
  await editor.locator('.home-button').evaluate(el => Promise.all(el.getAnimations().map(animation => animation.finished.catch(() => {}))));
  check(await editor.evaluate(el => getComputedStyle(el).backgroundColor !== 'rgb(255, 255, 255)'), 'AI screen uses app dark theme');
  await editor.screenshot({ path: 'output/playwright/ai-editor-dark-320.png' });
  await page.keyboard.press('Tab'); check(await page.evaluate(() => !!document.activeElement.closest('dialog')), 'keyboard focus stays in AI modal');
  await page.evaluate(() => document.documentElement.setAttribute('data-theme', 'light'));
  await feedback().fill('One last request to test switching to a different account.'); await control({ delay: true }); await generate();
  await editor.getByRole('heading', { name: 'Preparing your suggestion', exact: true }).waitFor({ timeout: 15000 });
  await page.evaluate(async module => { window.aiQaAuth = await import(module); await (await window.aiQaAuth.sb()).auth.signOut(); }, qa.authModule);
  await page.waitForFunction(() => !document.querySelector('dialog.course-editor'));
  check(true, 'account sign-out closes and clears AI editor');
  await signIn(qa.accounts[1]); await control({ release: true, delay: false }); await openEditor();
  check(await editor.getByRole('button', { name: 'Continue saved AI request', exact: true }).count() === 0, 'another account never sees the former account proposal');
  await editor.getByRole('button', { name: 'Close course editor' }).click();
  check(errors.length === 0, 'no browser exceptions: ' + errors.join('; '));
  const report = { total: checks.length, passed: checks, scope: 'Actual Home/review/editor/learner with local Auth/API/Postgres; synthetic provider; no paid or hosted acceptance.' };
  await page.evaluate(report => { window.__aiEditorReport = report; }, report); return report;
})
