(async page => {
  const qa=__IMAGE_UI_QA__,checks=[],errors=[];
  const check=(value,label)=>{if(!value)throw new Error(label);checks.push(label);};
  page.on('pageerror',error=>errors.push(error.message));
  const control=async body=>(await(body?page.request.post(qa.origin+'/api/qa/image-control',{data:body}):page.request.get(qa.origin+'/api/qa/image-control'))).json();
  const signIn=async account=>{const error=await page.evaluate(async({account,module})=>{window.imageQaAuth=await import(module);return(await(await window.imageQaAuth.sb()).auth.signInWithPassword({email:account.email,password:account.password})).error?.message;},{account,module:qa.authModule});check(!error,'actual local account signs in');await page.waitForFunction(owner=>window.imageQaAuth.getUser()?.id===owner,account.owner);};
  await signIn(qa.accounts[0]);
  const editor=page.locator('dialog.image-editor'),button=name=>editor.getByRole('button',{name,exact:true});
  const open=async()=>{await page.goto(qa.origin+'/?experience=workspace&filter=mine');await page.getByRole('link',{name:/^Review course\s*:\s*Image Studio Photography QA/}).click();await page.getByRole('button',{name:'Course images',exact:true}).click();await editor.getByRole('combobox',{name:'Choose a lesson',exact:true}).waitFor();};
  const ready=async()=>{await editor.getByRole('heading',{name:'2. Review the candidate',exact:true}).waitFor({timeout:15000});await page.waitForFunction(()=>!!document.querySelector('dialog.image-editor .image-preview img')?.complete);};
  const confirm=async()=>{await editor.locator('#image-consent').check();if(await editor.locator('#image-charge').count())await editor.locator('#image-charge').check();};
  await open();await editor.getByLabel('OpenAI API key',{exact:true}).waitFor();
  check((await editor.locator('[data-image-cost-guidance]').textContent()).includes('US$0.013 for 1 image.'),'generation consent shows server-matched image estimate plus prompt-token caveat');
  await editor.getByText('How image costs work',{exact:true}).click();
  check((await editor.locator('[data-image-cost-details]').textContent()).includes('439 image-output tokens'),'cost disclosure explains additional image tokens');
  check((await editor.locator('.image-coverage').textContent()).includes('0 of 3 lessons'),'image progress uses saved content, not planned requests');
  await button('Next image →').click();check(await editor.locator('#image-lesson').inputValue()==='1'&&(await control()).calls===0,'Next image only navigates and never charges');
  await editor.locator('#image-lesson').selectOption('0');
  await editor.getByText('View all lessons',{exact:true}).click();
  check(await editor.locator('[data-image-coverage]').getAttribute('open')!==null,'all-lesson disclosure opens');
  check((await control()).calls===0,'opening course images does not generate');
  await editor.getByLabel('OpenAI API key',{exact:true}).fill(qa.secret);await button('Connect OpenAI').click();
  await editor.getByText('OpenAI connected. No image has been generated.',{exact:false}).waitFor();
  check(await editor.locator('[data-image-cost-details]').getAttribute('open')!==null,'cost explanation stays open through connection refresh');
  check((await control()).calls===0&&(await control()).metadataCalls===1,'connection only validates metadata');
  check(await editor.locator('#image-key').count()===0,'secret input removed after connecting');
  check(await page.evaluate(secret=>!JSON.stringify({...localStorage}).includes(secret),qa.secret),'OpenAI key never stored in browser local storage');
  await button('Generate 1 image').click();await editor.getByRole('alert').waitFor();check((await control()).calls===0,'explicit billing consent required');
  await editor.getByLabel('Image description',{exact:true}).fill('🙂'.repeat(4001));await confirm();await button('Generate 1 image').click();
  check((await control()).calls===0&&(await editor.getByLabel('Image description',{exact:true}).inputValue()).length===8002,'Unicode limit rejects without truncating pasted text');
  await editor.getByLabel('Image description',{exact:true}).fill('Show an object beside a window, with soft light from the left and a shadow to the right.');
  await button('Next image →').click();await editor.getByRole('alert').waitFor();
  check(await editor.locator('#image-lesson').inputValue()==='0'&&(await editor.getByLabel('Image description',{exact:true}).inputValue()).includes('soft light'),'Next image protects unsent description edits');
  await editor.getByLabel('Image description',{exact:true}).fill('Show an object beside a window, with soft light from the left and a shadow to the right.');
  check(await editor.getByRole('alert').count()===0,'editing clears obsolete validation warning');
  for(const width of [1440,390,320]){await page.setViewportSize({width,height:1000});check(await editor.evaluate(el=>el.scrollWidth<=el.clientWidth),`${width}px request screen has no horizontal overflow`);await editor.evaluate(el=>el.scrollTop=0);await editor.screenshot({path:`output/playwright/image-studio-request-${width}.png`});await editor.evaluate(el=>el.scrollTop=el.scrollHeight);await editor.screenshot({path:`output/playwright/image-studio-confirm-${width}.png`});}
  await control({delay:true});let loseStart=true,loseSave=true,failAsset=true;
  await page.route('**/api/courses/images*',async route=>{
    if(route.request().method()==='POST'){
      const action=route.request().postDataJSON()?.action;
      if(action==='start'&&loseStart){loseStart=false;await route.fetch();return route.abort('failed');}
      if(action==='accept'&&loseSave){loseSave=false;await route.fetch();return route.abort('failed');}
    }else if(route.request().url().includes('action=asset')&&failAsset){failAsset=false;return route.abort('failed');}return route.continue();
  });
  await button('Generate 1 image').click();await button('Check same request').waitFor();
  await page.waitForFunction(()=>!document.querySelector('[data-image-action="check-start"]')?.disabled&&!!document.querySelector('#image-error'));
  await button('Check same request').click();await editor.getByRole('heading',{name:'Generating image',exact:true}).waitFor();
  check((await control()).calls===1,'lost start reply recovers same attempt without second paid dispatch');
  await button('Cancel attempt').focus();await page.waitForTimeout(2300);
  check(await button('Cancel attempt').evaluate(el=>el===document.activeElement),'background progress refresh preserves keyboard focus');
  await button('Close course images').click();check(await editor.count()===0,'persisted request can close without a false loss warning');
  await open();await editor.getByRole('heading',{name:'Generating image',exact:true}).waitFor();
  check((await control()).calls===1,'refresh finds account request without regeneration');
  await control({release:true,delay:false});await button('Check this attempt').click();await button('Retry image loading').waitFor();
  check(await button('Use this image').isDisabled(),'unavailable preview cannot be blindly accepted');
  await button('Retry image loading').click();await ready();check((await control()).calls===1,'retrying private image download does not regenerate');
  check((await editor.locator('.image-coverage').textContent()).includes('1 awaiting review')&&(await editor.locator('.image-coverage').textContent()).includes('0 of 3 lessons'),'candidate ready does not become saved coverage');
  check(!(await control()).image,'ready candidate has not changed the saved lesson');
  for(const width of [1440,390,320]){await page.setViewportSize({width,height:1000});check(await editor.evaluate(el=>el.scrollWidth<=el.clientWidth),`${width}px review screen has no horizontal overflow`);await editor.evaluate(el=>el.scrollTop=0);await editor.screenshot({path:`output/playwright/image-studio-review-${width}.png`});await editor.evaluate(el=>el.scrollTop=el.scrollHeight);await editor.screenshot({path:`output/playwright/image-studio-accept-${width}.png`});}
  await page.evaluate(()=>document.documentElement.setAttribute('data-theme','dark'));await editor.screenshot({path:'output/playwright/image-studio-review-dark-320.png'});
  check(await editor.evaluate(el=>getComputedStyle(el).backgroundColor!=='rgb(255, 255, 255)'),'review follows dark theme');
  await page.keyboard.press('Tab');check(await page.evaluate(()=>!!document.activeElement.closest('dialog')),'keyboard focus stays in modal');
  await page.evaluate(()=>document.documentElement.setAttribute('data-theme','light'));
  await button('Use this image').click();check(!(await control()).image,'human review required before accepting');
  await editor.getByLabel('Alternative text',{exact:true}).fill('Soft light falls on a small object from the left, casting its shadow to the right.');
  await editor.getByLabel('Caption (optional)',{exact:true}).fill('Compare the light side with the shadow side.');
  await editor.locator('#image-reviewed').check();await button('Use this image').click();await button('Check same save').waitFor();
  await page.waitForFunction(()=>!document.querySelector('[data-image-action="accept"]')?.disabled&&!!document.querySelector('#image-error'));
  const firstImage=(await control()).image;check(!!firstImage&&!firstImage.src,'save commits stable asset identity despite lost reply');
  await button('Check same save').click();await editor.getByRole('heading',{name:'Image added to the lesson',exact:true}).waitFor();
  check((await editor.locator('.image-coverage').textContent()).includes('1 of 3 lessons'),'explicit acceptance updates saved coverage');
  check((await control()).calls===1,'acceptance replay never generates');
  failAsset=true;await editor.getByRole('link',{name:'Open updated lesson →',exact:true}).click();
  await page.getByRole('button',{name:'Retry image',exact:true}).waitFor();
  check(await page.locator('[data-private-image-description]').textContent()===firstImage.alt,'learner keeps reviewed description visible when private image cannot load');
  await page.getByRole('button',{name:'Retry image',exact:true}).click();
  await page.waitForFunction(()=>document.querySelector('[data-private-image] img')?.naturalWidth>0);
  check((await control()).calls===1,'learner image retry downloads same asset without generating');
  check(await page.locator('[data-private-image] img').getAttribute('alt')===firstImage.alt,'learner loads private accepted PNG with reviewed alt text');
  await page.screenshot({path:'output/playwright/image-studio-learner-320.png',fullPage:true});
  await page.reload();await page.waitForFunction(()=>document.querySelector('[data-private-image] img')?.naturalWidth>0);check(true,'accepted asset survives actual learner reload');
  await open();await button('Generate a replacement').click();await confirm();await button('Generate 1 replacement').click();await ready();
  check((await editor.locator('.image-coverage').textContent()).includes('1 of 3 lessons')&&(await editor.locator('.image-coverage').textContent()).includes('Current image kept'),'replacement review retains accepted image in progress');
  check((await control()).image.asset_id===firstImage.asset_id,'unaccepted replacement leaves old lesson image');
  check(await editor.getByText('Currently in the lesson',{exact:true}).isVisible(),'comparison shows current image beside candidate');
  await editor.screenshot({path:'output/playwright/image-studio-replacement-320.png'});
  await button('Discard candidate').click();await editor.getByRole('heading',{name:'Candidate discarded',exact:true}).waitFor();
  check((await control()).image.asset_id===firstImage.asset_id,'discard preserves accepted image');
  await control({outcome:'quota'});await confirm();await button('Generate 1 replacement').click();await editor.getByRole('heading',{name:'Image needs attention',exact:true}).waitFor({timeout:15000});
  check(await editor.getByLabel('Image description',{exact:true}).inputValue()!=='','failure keeps description and offers explicit retry');
  const failedCalls=(await control()).calls;await button('Close course images').click();await open();check((await control()).calls===failedCalls,'reopening failure does not retry automatically');
  await control({outcome:'ok',delay:true});await confirm();await button('Generate 1 replacement').click();await editor.getByRole('heading',{name:'Generating image',exact:true}).waitFor();
  await button('Cancel attempt').click();await editor.getByRole('heading',{name:'Attempt cancelled',exact:true}).waitFor();await control({release:true,delay:false});
  check((await control()).image.asset_id===firstImage.asset_id,'cancellation retains saved image');
  await confirm();await button('Generate 1 replacement').click();await ready();await control({edit:true});await editor.locator('#image-reviewed').check();await button('Use this image').click();await editor.getByRole('alert').waitFor();
  check((await editor.getByRole('alert').textContent()).includes('lesson changed'),'stale lesson rejected without overwriting content');
  check((await control()).image.asset_id===firstImage.asset_id&&(await control()).title==='Newer saved lesson','stale acceptance preserves newer saved lesson');
  await button('Discard candidate').click();await confirm();await button('Generate 1 replacement').click();await ready();check((await control()).calls===6,'discarding stale candidate refreshes lesson before a new explicit request');
  await editor.getByLabel('Alternative text',{exact:true}).fill('Unsent review change');await button('Close course images').click();await editor.getByRole('heading',{name:'Leave image editing?',exact:true}).waitFor();await button('Keep editing').click();
  check(await editor.getByLabel('Alternative text',{exact:true}).inputValue()==='Unsent review change','closing warning preserves unsent review edits');
  await page.evaluate(async module=>{window.imageQaAuth=await import(module);await(await window.imageQaAuth.sb()).auth.signOut();},qa.authModule);await page.waitForFunction(()=>!document.querySelector('dialog.image-editor'));check(true,'sign-out closes private editor');
  await signIn(qa.accounts[1]);await open();await editor.getByLabel('OpenAI API key',{exact:true}).waitFor();check(await editor.locator('.image-preview').count()===0,'second account sees neither key nor candidate from first account');
  await button('Close course images').click();check(errors.length===0,'no browser exceptions: '+errors.join('; '));
  const report={total:checks.length,passed:checks,scope:'Actual app with isolated local Auth/API/Postgres/Storage; synthetic images only; no paid or hosted acceptance.'};await page.evaluate(report=>window.__imageUIReport=report,report);return report;
})
