(async page=>{
 const qa=__MODERATION_QA__,checks=[],errors=[],writes=[];const check=(v,label)=>{if(!v)throw new Error(label);checks.push(label);};page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(r.url().includes('/api/courses/moderation')&&r.method()==='POST')writes.push(r.postData());});
 const url=qa.origin+'/?experience=workspace&moderation=reports&report='+qa.reportId;
 const signIn=async index=>page.evaluate(async({module,a})=>{const auth=await import(module),r=await(await auth.sb()).auth.signInWithPassword(a);if(r.error)throw r.error;},{module:qa.authModule,a:qa.accounts[index]});
 await page.getByText('Sign in to review reports.',{exact:true}).waitFor();check(await page.locator('[data-decision-note]').count()===0,'guest does not receive case content');
 await signIn(1);await page.goto(url);await page.getByText('Moderator access is required.',{exact:true}).waitFor();check(await page.locator('[data-decision-note]').count()===0&&await page.getByRole('link',{name:'Reports',exact:true}).count()===0,'ordinary reporter has no moderation controls or nav');
 await signIn(2);await page.goto(qa.origin+'/?experience=workspace&moderation=reports');await page.locator('[data-review-filter]').selectOption('closed');await page.waitForFunction(()=>document.querySelectorAll('.moderation-list article').length===20);await page.getByRole('button',{name:'Load more reports',exact:true}).click();await page.waitForFunction(()=>document.querySelectorAll('.moderation-list article').length>20);check(true,'reviewed queue loads additional cases');
 await page.goto(url);await page.locator('[data-decision-note]').waitFor();check(await page.getByRole('link',{name:'Reports',exact:true}).isVisible(),'assigned moderator has Reports entry outside collection tabs');
 check(await page.locator('.moderation-report img').count()===0&&!await page.evaluate(()=>!!window.reportAttack),'reported hostile markup stays text');
 check(!(await page.locator('body').textContent()).includes('PRIVATE-'),'private course fields never appear');
 await page.locator('[data-review-evidence] > summary').click();await page.locator('[data-review-evidence] > details > summary').first().click();await page.waitForFunction(()=>[...document.querySelectorAll('[data-shared-image] img')].some(img=>!img.hidden&&img.naturalWidth>0));
 check(true,'authorized moderator can inspect captured public image');
 await page.getByRole('button',{name:'Remove from Community',exact:true}).click();await page.getByText('Write a decision note of 10–2,000 characters first.',{exact:true}).waitFor();check(await page.locator('dialog[open]').count()===0,'note required before confirmation');
 const note=page.locator('[data-decision-note]');await note.fill('Synthetic browser decision: remove this fixture only.');
 await page.getByRole('button',{name:'Remove from Community',exact:true}).click();let dialog=page.locator('dialog.moderation-confirm');await dialog.waitFor();check((await dialog.textContent()).includes('private course remains saved'),'confirmation explains scope and preserved private course');
 await page.keyboard.press('Shift+Tab');check(await page.evaluate(()=>document.activeElement?.closest('dialog')!==null),'keyboard focus stays in confirmation');await dialog.getByRole('button',{name:'Cancel',exact:true}).click();check(writes.length===0&&await note.inputValue()==='Synthetic browser decision: remove this fixture only.','cancel preserves note and performs no write');
 // A stale decision response must retain the note and require refreshed evidence.
 await page.route('**/api/courses/moderation',route=>route.fulfill({status:409,json:{code:'conflict',error:'The case or publication changed. Refresh it before deciding. Your note has not been discarded.'}}));
 await page.getByRole('button',{name:'Remove from Community',exact:true}).click();await dialog.getByRole('button',{name:'Confirm removal',exact:true}).click();await page.getByText('The case or publication changed.',{exact:false}).waitFor();check((await note.inputValue()).includes('fixture only'),'conflict retains decision note');await page.unroute('**/api/courses/moderation');await page.getByRole('button',{name:'Refresh',exact:true}).click();await note.waitFor();
 let lost=true;await page.route('**/api/courses/moderation',async route=>{if(route.request().method()==='POST'&&lost){lost=false;await route.fetch();await route.fulfill({status:503,json:{error:'The decision could not be confirmed. Retry the same decision.'}});}else await route.continue();});
 await page.getByRole('button',{name:'Remove from Community',exact:true}).click();await dialog.getByRole('button',{name:'Confirm removal',exact:true}).click();await dialog.getByRole('button',{name:'Retry same decision',exact:true}).waitFor();const submitted=JSON.parse(writes.at(-1));await dialog.getByRole('button',{name:'Retry same decision',exact:true}).click();await page.getByText('This decision was already recorded.',{exact:false}).waitFor();check(JSON.parse(writes.at(-1)).operationId===submitted.operationId,'uncertain-response retry reuses decision operation');await page.unroute('**/api/courses/moderation');
 await page.getByText('Public sharing restricted.',{exact:false}).waitFor();check(true,'confirmed removal shows current restricted state');
 check(await page.evaluate(async id=>(await fetch('/api/courses/community?courseId='+id)).status,qa.publicId)===404,'UI removal really revokes guest course access');
 for(const width of [1440,390,320]){await page.setViewportSize({width,height:1000});await page.locator('h1').scrollIntoViewIfNeeded();check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`moderation detail fits ${width}px`);check(await page.evaluate(()=>[...document.querySelectorAll('.header-right button,.experience-nav a')].filter(el=>el.getBoundingClientRect().width>0).every(el=>{const r=el.getBoundingClientRect();return r.left>=0&&r.right<=innerWidth;})),`header controls remain fully visible at ${width}px`);await page.screenshot({path:`output/playwright/moderation-review-${width}.png`});}
 await page.evaluate(()=>document.documentElement.setAttribute('data-theme','dark'));await page.waitForTimeout(250);await page.screenshot({path:'output/playwright/moderation-review-dark-320.png'});await page.evaluate(()=>document.documentElement.setAttribute('data-theme','light'));
 await signIn(0);await page.goto(qa.origin+'/?experience=workspace&filter=mine');const card=page.locator('[data-home-course="'+qa.courseId+'"]');await card.getByText('Public sharing restricted',{exact:true}).waitFor();check(await card.getByRole('button',{name:'Review and publish again',exact:true}).count()===0,'creator card does not invite blocked republishing');await card.getByRole('button',{name:'View sharing status',exact:true}).click();await page.getByRole('heading',{name:'Public sharing restricted',exact:true}).waitFor();check(await page.locator('[data-publication-dialog] [data-pub="preview"]').count()===0,'restricted management explains rather than offering republish');await page.getByRole('button',{name:'Back to Your Courses',exact:true}).click();
 await signIn(2);await page.goto(url);await page.getByRole('button',{name:'Allow publishing again',exact:true}).waitFor();await note.fill('Synthetic browser review: allow this creator to publish again.');await page.getByRole('button',{name:'Allow publishing again',exact:true}).click();dialog=page.locator('dialog.moderation-confirm');check((await dialog.textContent()).includes('keeps the course unpublished'),'restoration confirmation is not automatic publication');await dialog.getByRole('button',{name:'Confirm permission change',exact:true}).click();await page.getByText('Publishing permission restored.',{exact:false}).waitFor();check(await note.count()===0,'closed unrestricted case has no misleading decision form');check(await page.evaluate(async id=>(await fetch('/api/courses/community?courseId='+id)).status,qa.publicId)===404,'permission restore keeps public access off');
 await page.locator('.moderation-card').last().getByText('Synthetic browser decision: remove this fixture only.',{exact:true}).waitFor();check(true,'decision audit visible only in moderator workspace');
 await page.route('**/api/courses/moderation?reportId=*',route=>route.fulfill({status:403,json:{code:'forbidden',error:'Moderator access is required.'}}));await page.getByRole('button',{name:'Refresh',exact:true}).click();await page.getByText('Moderator access is required.',{exact:true}).waitFor();check(await page.locator('[data-review-evidence]').count()===0,'permission denial clears protected evidence');await page.unroute('**/api/courses/moderation?reportId=*');
 await page.goto(url);await page.getByRole('heading',{name:'Decision history',exact:true}).waitFor();await page.evaluate(async module=>{await(await(await import(module)).sb()).auth.signOut();},qa.authModule);await page.getByText('Sign in to review reports.',{exact:true}).waitFor();check(await page.locator('[data-review-evidence]').count()===0,'sign-out clears evidence and decision state');
 check(errors.length===0,'no browser exceptions: '+errors.join('; '));const result={total:checks.length,checks};await page.evaluate(result=>window.__moderationReport=result,result);return result;
})
