(async page => {
  const checks = [], errors = [];
  const check = (value, label) => { if (!value) throw new Error(label); checks.push(label); };
  page.on('pageerror', error => errors.push(error.message));
  await page.evaluate(() => window.__reviewQA?.editor?.destroy());
  await page.route('**/qa-review-sources', route => route.fulfill({ contentType: 'text/html', body: '<!doctype html><html lang="en"><head><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="/styles/tokens.css"><link rel="stylesheet" href="/styles/base.css"><link rel="stylesheet" href="/styles/themes.css"><link rel="stylesheet" href="/styles/components.css"><link rel="stylesheet" href="/styles/home.css"></head><body data-experience="workspace"><div class="intake-modal"><div class="intake-card" role="dialog" aria-modal="true" id="review-host"></div></div></body></html>' }));
  await page.goto('http://127.0.0.1:4173/qa-review-sources');
  await page.evaluate(async () => {
    const { mountReviewSourceEditor } = await import('/js/review-source-editor.js?v=1');
    const { setupDraft } = await import('/js/setup-model.js?v=1');
    const { prepareAccountPayload } = await import('/js/setup-account-model.js?v=1');
    const q = window.__reviewQA = { checks: 0, applies: [], back: 0, started: 0, failCheck: false, failApply: false };
    const draft = setupDraft('A practical photography course'); draft.brief.audience = 'Beginners'; draft.components = ['lessons'];
    draft.sources.notes = [{ id: 'interview', title: 'Workshop transcript', text: 'Start by looking at natural light.' }];
    q.show = () => {
      q.editor?.destroy();
      q.editor = mountReviewSourceEditor(document.querySelector('#review-host'), { jobId: 'job-browser-qa', owner: 'qa-owner', onBack: () => { q.back++; }, onStarted: () => { q.started++; }, client: {
        read: async () => ({ draft: structuredClone(draft), runId: 'original-run', legacyFiles: [], storageId: 'qa-sources' }),
        check: async (owner, job, state, edited) => {
          q.checks++; if (q.failCheck) throw new Error('Upload failed. Your accepted sources are unchanged. Retry.');
          const { payload } = await prepareAccountPayload(edited);
          const files = await Promise.all(edited.sources.files.map(async file => ({ id: file.id, name: file.name, kind: 'txt', status: 'ready', text: await file.blob.text(), characters: file.size, warnings: [] })));
          return { sources: { files, complete: true, requiresReview: !!files.length, characters: 200, limit: 48000, digest: 'checked-digest' }, issues: [], changes: { sources: payload.sources, expectedRunId: state.runId, sourceReview: 'checked-digest' } };
        },
        apply: async (owner, job, changes) => {
          q.applies.push(changes); if (q.failApply) throw new Error('This review changed in another tab. Your edits have not replaced it.');
          await new Promise(resolve => { q.finishApply = resolve; });
        }
      } });
    };
    q.show();
  });
  const note = () => page.getByLabel('Notes, transcript or raw text', { exact: true }).first();
  const checkSources = () => page.getByRole('button', { name: 'Check source changes', exact: true });
  const apply = () => page.getByRole('button', { name: 'Use sources and recheck research', exact: true });
  const fits = () => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth);
  await note().waitFor();
  check((await note().inputValue()).includes('natural light'), 'accepted note restored into shared editor');
  check(await page.getByRole('heading', { name: 'Adjust your sources', exact: true }).evaluate(el => el === document.activeElement), 'editor heading receives focus');
  check(await page.getByText('12,000 characters per note', { exact: false }).isVisible(), 'transcript limit explained');
  await note().fill('🏊'.repeat(12001));
  check(await note().getAttribute('aria-invalid') === 'true', 'oversized Unicode note is marked without truncation');
  await page.getByRole('button', { name: 'Split into smaller notes', exact: true }).first().click();
  check(await page.getByLabel('Notes, transcript or raw text', { exact: true }).count() === 2, 'oversized note splits into two');
  check((await page.getByLabel('Notes, transcript or raw text', { exact: true }).evaluateAll(nodes => nodes.map(node => node.value))).join('') === '🏊'.repeat(12001), 'splitting is lossless');
  await note().fill('New transcript: teach the learner how to find soft window light.');
  await page.getByRole('button', { name: 'Remove note', exact: true }).last().click();
  await page.getByRole('button', { name: 'Undo removal', exact: true }).click();
  check(await page.getByLabel('Notes, transcript or raw text', { exact: true }).count() === 2, 'source removal can be undone');
  await page.getByRole('button', { name: 'Remove note', exact: true }).last().click();
  await page.getByRole('button', { name: /^Links/ }).click();
  await page.getByRole('button', { name: '+ Add a link', exact: true }).click();
  await page.getByLabel('Website URL', { exact: true }).fill('not-a-url');
  check(await page.getByLabel('Website URL', { exact: true }).getAttribute('aria-invalid') === 'true', 'invalid URL has inline error');
  await checkSources().click();
  await page.locator('[data-editor-error]').getByText('Enter a complete link', { exact: false }).waitFor();
  check(await page.getByLabel('Website URL', { exact: true }).inputValue() === 'not-a-url', 'check failure preserves typed URL');
  await page.getByLabel('Website URL', { exact: true }).fill('https://example.com/photography');
  await page.getByRole('button', { name: /^Files/ }).click();
  await page.locator('#source-files').setInputFiles(['/Users/davidwang/Learnable/scripts/fixtures/review-sources/interview.txt', '/Users/davidwang/Learnable/scripts/fixtures/review-sources/unsupported.csv']);
  check(await page.getByRole('heading', { name: 'interview.txt', exact: true }).isVisible(), 'valid file accepted in mixed batch');
  check(await page.getByText('unsupported.csv: Choose a PDF, DOCX or TXT file.', { exact: false }).isVisible(), 'unsupported file is rejected without losing good file');
  await page.evaluate(() => { window.__reviewQA.failCheck = true; });
  await checkSources().click();
  await page.locator('[data-editor-error]').getByText('Upload failed.', { exact: false }).waitFor();
  check(await page.getByRole('heading', { name: 'interview.txt', exact: true }).isVisible(), 'upload failure retains selected file');
  await page.evaluate(() => { window.__reviewQA.failCheck = false; });
  await checkSources().click();
  const consent = () => page.getByRole('checkbox', { name: 'I’ve checked the extracted text and want to use it.', exact: true });
  await consent().waitFor();
  check(await apply().isDisabled(), 'file acknowledgement required before recheck');
  check(await page.evaluate(() => window.__reviewQA.applies.length === 0), 'editing/checking never starts AI');
  await page.getByText('Preview text from interview.txt', { exact: true }).click();
  check((await page.getByLabel('Extracted text from interview.txt', { exact: true }).textContent()).includes('<script>'), 'raw text is escaped in preview');
  check(await page.evaluate(() => !window.unsafeSource), 'source markup cannot execute');
  await page.setViewportSize({ width: 1440, height: 1100 });
  await page.bringToFront();
  await page.locator('.intake-modal').evaluate(el => { el.scrollTop = 0; });
  await page.screenshot({ path: 'output/playwright/review-sources-1440.png', fullPage: true, animations: 'disabled' });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.locator('.intake-modal').evaluate(el => { el.scrollTop = 0; });
  check(await fits(), 'editor fits 390px mobile');
  await page.screenshot({ path: 'output/playwright/review-sources-390.png', fullPage: true, animations: 'disabled' });
  await page.setViewportSize({ width: 320, height: 568 });
  check(await fits(), 'editor fits 320px mobile');
  await consent().focus(); await page.keyboard.press('Space');
  check(await apply().isEnabled(), 'keyboard acknowledgement enables explicit recheck');
  await page.getByRole('button', { name: /^Plain notes/ }).click();
  await note().fill('Updated after the file check.');
  check(await apply().isHidden() && await checkSources().isVisible(), 'editing invalidates checked source digest and consent');
  page.once('dialog', dialog => dialog.dismiss());
  await page.getByRole('button', { name: 'Back to research review', exact: true }).click();
  check(await page.evaluate(() => window.__reviewQA.back === 0), 'cancel confirmation can keep unsaved edits');
  await checkSources().click(); await consent().check();
  await page.evaluate(() => { window.__reviewQA.failApply = true; });
  await apply().click();
  await page.getByText('This review changed in another tab.', { exact: false }).waitFor();
  check(await note().inputValue() === 'Updated after the file check.', 'stale checkpoint rejection preserves edits');
  await page.evaluate(() => { window.__reviewQA.failApply = false; });
  await apply().click();
  check(await apply().isDisabled() && await page.getByRole('button', { name: 'Back to research review', exact: true }).isDisabled(), 'in-flight submission prevents double submit or ambiguous cancellation');
  await page.evaluate(() => window.__reviewQA.finishApply());
  await page.waitForFunction(() => window.__reviewQA.started === 1);
  check(await page.evaluate(() => window.__reviewQA.applies.at(-1).sourceReview === 'checked-digest'), 'submission includes acknowledged digest');
  check(await page.evaluate(() => window.__reviewQA.applies.at(-1).sources.notes[0].text === 'Updated after the file check.'), 'submission includes current note, not old checked input');
  await page.evaluate(() => window.__reviewQA.show()); await note().waitFor();
  await note().fill('Discard this change'); page.once('dialog', dialog => dialog.accept());
  await page.getByRole('button', { name: 'Back to research review', exact: true }).click();
  check(await page.evaluate(() => window.__reviewQA.back === 1), 'confirmed cancel returns without source submission');
  await page.goto('http://127.0.0.1:4173/?experience=workspace');
  await page.getByRole('heading', { name: 'What will you learn next?', exact: true }).waitFor();
  await page.evaluate(async () => {
    const { ensureJob } = await import('/js/jobs.js?v=3');
    const { openIntakeForJob } = await import('/js/intake.js?v=82');
    ensureJob('job-ui-source-entry-qa', { topic: 'Source entry QA' }, { runner: 'cloud', status: 'review_research', stage: 'research', review: { researchResults: [{ mod: { id: 'light', title: 'Window light' }, bundle: { key_concepts: ['Soft light'], examples: ['Window portrait'] } }] } });
    openIntakeForJob('job-ui-source-entry-qa');
  });
  check(await page.getByRole('button', { name: 'Adjust sources', exact: true }).isVisible(), 'actual intake checkpoint exposes source editor entry');
  await page.locator('[data-review-feedback]').fill('Keep the practice simple.');
  await page.getByRole('button', { name: 'Adjust sources', exact: true }).click();
  await page.locator('[data-editor-error]').getByText('Your account changed.', { exact: false }).waitFor();
  check(await page.getByRole('dialog', { name: 'Adjust sources', exact: true }).isVisible(), 'actual intake mounts shared editor and handles missing session');
  await page.keyboard.press('Escape');
  check(await page.locator('[data-review-feedback]').inputValue() === 'Keep the practice simple.', 'return from source editor preserves existing research feedback');
  check(await page.getByRole('button', { name: 'Adjust sources', exact: true }).evaluate(el => el === document.activeElement), 'return restores focus to entry action');
  await page.getByRole('button', { name: 'Close', exact: true }).filter({ visible: true }).first().click();
  await page.evaluate(async () => { const { removeJob } = await import('/js/jobs.js?v=3'); removeJob('job-ui-source-entry-qa'); });
  check(errors.length === 0, `no browser exceptions: ${errors.join('; ')}`);
  await page.evaluate(report => { window.__reviewQA = { report }; }, { checks: checks.length, passed: checks, provider: 'injected fixture plus actual intake entry; no AI calls' });
  return { checks: checks.length, passed: checks, provider: 'injected fixture; no AI calls' };
})
