(async page => {
  const base = 'http://127.0.0.1:4173', mail = 'http://127.0.0.1:54324';
  const checks = [], errors = [], writes = [];
  const check = (ok, name) => { if (!ok) throw new Error(name); checks.push(name); };
  page.on('pageerror', error => errors.push(error.message));
  page.on('request', req => { if (req.method() === 'POST') writes.push(req.url()); });
  await page.goto(`${base}/?experience=workspace`);
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.getByLabel('What do you want to learn or teach?').fill('Review sign-in journey QA');
  await page.getByRole('button', { name: 'Create course', exact: true }).click();
  await page.getByLabel('Who is it for?').waitFor();
  check(await page.getByRole('dialog').count() === 0, 'Home Create opens guest setup, not authentication');
  await page.getByRole('navigation', { name: 'Course setup steps' }).getByRole('link', { name: 'Review', exact: true }).click();
  await page.getByRole('button', { name: 'Create course' }).click();
  await page.getByLabel('Who is it for?').waitFor();
  check(await page.getByRole('dialog').count() === 0, 'incomplete Review fixes required input before sign-in');
  await page.getByLabel('Who is it for?').fill('A learner testing contextual sign-in');
  await page.getByRole('button', { name: 'Continue to Experience' }).click();
  await page.getByRole('button', { name: 'Continue to Context' }).click();
  await page.getByRole('button', { name: '+ Add a note', exact: true }).click();
  await page.getByLabel('Notes, transcript or raw text').fill('Original transcript retained through contextual sign-in.');
  await page.getByRole('button', { name: /^Links/ }).click();
  await page.getByRole('button', { name: '+ Add a link', exact: true }).click();
  await page.getByLabel('Website URL').fill('https://example.com/review-signin');
  await page.getByRole('button', { name: /^Files/ }).click();
  await page.getByLabel('Choose files or drop them here').setInputFiles('/Users/davidwang/Learnable/scripts/fixtures/local-backup-original.txt');
  await page.getByRole('button', { name: 'Review setup' }).click();
  await page.getByRole('button', { name: 'Create course' }).waitFor();
  check(!writes.some(url => /\/auth\/v1\/otp|\/api\/setups\/store|\/storage\/v1\/object/.test(url)), 'all four steps perform no sign-in, upload or account-save requests');
  check(!await page.getByRole('button', { name: 'Download setup' }).isVisible(), 'routine browser-save controls are not part of setup UI');
  await page.screenshot({ path: 'output/playwright/review-create-1440.png', fullPage: true });
  await page.getByRole('button', { name: 'Create course' }).click();
  await page.getByRole('dialog', { name: 'Sign in to create your course' }).waitFor();
  check(await page.locator('[data-setup-root]').count() === 1, 'sign-in overlays the selected Review instead of adding a fifth step');
  await page.screenshot({ path: 'output/playwright/review-signin-dialog-1440.png' });
  await page.keyboard.press('Escape');
  await page.getByRole('button', { name: 'Create course' }).waitFor();
  check(await page.getByRole('dialog').count() === 0 && await page.getByText('1 note · 1 link · 1 file', { exact: true }).isVisible(), 'Escape returns to Review with all sources');
  check(await page.getByRole('button', { name: 'Create course' }).evaluate(el => document.activeElement === el), 'dismissal restores focus to Create course');
  await page.getByRole('button', { name: 'Create course' }).click();
  await page.getByLabel('Email address').fill('not-an-email');
  await page.getByRole('button', { name: 'Continue with email' }).click();
  await page.getByText('Enter a complete email address.', { exact: true }).waitFor();
  check(await page.getByLabel('Email address').inputValue() === 'not-an-email', 'validation preserves the entered email');
  await page.route('**/auth/v1/otp**', route => route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ msg: 'QA email service unavailable' }) }));
  const email = `review-signin-${Date.now()}@example.test`;
  await page.getByLabel('Email address').fill(email);
  await page.getByRole('button', { name: 'Continue with email' }).click();
  await page.locator('#setup-signin-error').filter({ hasText: /.+/ }).waitFor();
  check(await page.getByLabel('Email address').inputValue() === email, 'email service failure preserves email and setup for retry');
  await page.unroute('**/auth/v1/otp**');
  await page.getByRole('button', { name: 'Continue with email' }).click();
  await page.getByRole('heading', { name: 'Check your email', exact: true }).waitFor();
  check(await page.getByRole('button', { name: 'Resend sign-in link' }).isDisabled(), 'pending email has a resend cooldown');
  await page.setViewportSize({ width: 390, height: 844 });
  check(await page.getByRole('dialog').evaluate(el => { const r=el.getBoundingClientRect(); return r.left >= 0 && r.right <= innerWidth && el.scrollWidth <= el.clientWidth; }), 'mobile dialog fits without horizontal clipping');
  await page.screenshot({ path: 'output/playwright/review-signin-email-390.png' });
  await page.getByRole('button', { name: 'Back to review', exact: true }).click();
  await page.getByRole('button', { name: 'Create course' }).click();
  await page.getByRole('heading', { name: 'Check your email', exact: true }).waitFor();
  check(true, 'closing and reopening retains email-pending state');
  let selected;
  for (let i = 0; i < 30; i++) {
    const data = await (await page.request.get(`${mail}/api/v1/messages`)).json();
    selected = data.messages.find(item => item.To?.some(to => to.Address === email));
    if (selected) break;
    await page.waitForTimeout(250);
  }
  if (!selected) throw new Error('Local verification email did not arrive');
  const message = await (await page.request.get(`${mail}/api/v1/message/${selected.ID}`)).json();
  const link = message.HTML.match(/href="([^"]+)"/)?.[1]?.replaceAll('&amp;', '&');
  if (!link?.startsWith('http://127.0.0.1:54321/auth/v1/verify?')) throw new Error('Unexpected email destination');
  const callback = await page.context().newPage();
  try {
    await callback.goto(link);
    await page.locator('.setup-create-context').filter({ hasText: email }).waitFor();
    await callback.locator('.setup-create-context').filter({ hasText: email }).waitFor();
    check(await page.getByRole('dialog').count() === 0 && await callback.getByRole('dialog').count() === 0, 'real email sign-in returns both tabs to Review with no backup confirmation');
  } finally { await callback.close(); }
  const preserved = await page.evaluate(async () => {
    const { getUser } = await import('/js/auth.js?v=26');
    const { createDraftStore } = await import('/js/draft-store.js?v=3');
    const id = new URLSearchParams(location.search).get('draft'), store = createDraftStore();
    const record = await store.load(id, getUser().id), guest = await store.load(id, null);
    return { guest: guest.status, topic: record.draft.brief.topic, note: record.draft.sources.notes[0].text, url: record.draft.sources.links[0].url, original: await record.draft.sources.files[0].blob.text() };
  });
  check(preserved.guest === 'missing' && preserved.topic === 'Review sign-in journey QA' && preserved.note.startsWith('Original transcript') && preserved.url.endsWith('/review-signin') && preserved.original.includes('Original local browser QA transcript.'), 'only selected setup attaches to account scope with notes, URL and original bytes');
  await page.reload();
  await page.locator('.setup-create-context').filter({ hasText: email }).waitFor();
  check(await page.getByText('1 note · 1 link · 1 file', { exact: true }).isVisible(), 'signed-in Review and sources survive reload');
  await page.getByRole('button', { name: 'Create course' }).click();
  await page.getByRole('heading', { name: 'Connect Claude to create your plan' }).waitFor();
  check(await page.getByRole('dialog').count() === 0, 'signed-in Create bypasses sign-in and reaches provider readiness');
  check(await page.getByRole('button', { name: 'Save to account' }).count() === 0, 'no Save to account action remains in the creation flow');
  await page.evaluate(() => scrollTo({ top: 0, behavior: 'instant' }));
  await page.screenshot({ path: 'output/playwright/review-signedin-390.png', fullPage: true });
  check(!writes.some(url => /\/api\/gen\/(start|resume|review)/.test(url)), 'no paid generation is triggered by authentication or readiness');
  check(writes.some(url => /\/api\/setups\/store/.test(url)) && writes.some(url => /\/storage\/v1\/object/.test(url)), 'Create saves the signed-in request and original file to its account');
  const savedOriginal = await page.evaluate(async () => {
    const { getUser } = await import('/js/auth.js?v=26');
    const { createSetupAccountClient } = await import('/js/setup-account-client.js?v=2');
    const id = new URLSearchParams(location.search).get('draft');
    const restored = await createSetupAccountClient().restore(getUser().id, id);
    return await restored.draft.sources.files[0].blob.text();
  });
  check(savedOriginal.includes('Original local browser QA transcript.'), 'real browser upload restores original bytes from the account');
  await page.reload();
  await page.getByRole('heading', { name: 'Connect Claude to create your plan' }).waitFor();
  check(await page.getByRole('button', { name: 'Create course plan →', exact: true }).count() === 0, 'refresh checks readiness but cannot start without a provider connection');
  check(errors.length === 0, 'no uncaught JavaScript errors');
  return { checks, total: checks.length, retained: 'One synthetic local email account and its selected account setup with source original; no course generated or provider called.' };
})
