(async page => {
  const checks = [], errors = [], requests = [];
  const check = (ok, name) => { if (!ok) throw new Error(name); checks.push(name); };
  page.on('pageerror', e => errors.push(e.message));
  await page.route('**/qa-workspace-account', route => route.fulfill({ contentType: 'text/html', body: `<!doctype html><html lang="en"><head><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="/styles/tokens.css"><link rel="stylesheet" href="/styles/base.css"><link rel="stylesheet" href="/styles/themes.css"><link rel="stylesheet" href="/styles/components.css"><link rel="stylesheet" href="/styles/home.css"></head><body data-experience="workspace"><header class="header-right"><button id="theme-toggle">Theme</button></header><main class="app-main"><div id="content"></div></main></body></html>` }));
  await page.route('**/js/config.js*', route => route.fulfill({ contentType: 'text/javascript', body: 'export const SUPABASE_URL="https://workspace-qa.invalid"; export const SUPABASE_ANON_KEY="synthetic-public"; export const CREATION_IMAGES_ENABLED=false;' }));
  await page.route('https://esm.sh/@supabase/supabase-js@2', route => route.fulfill({ contentType: 'text/javascript', body: `export function createClient(){ return {auth:{getSession:async()=>({data:{session:window.__accountQA.user?{user:window.__accountQA.user,access_token:'synthetic-session'}:null}}),onAuthStateChange:fn=>{window.__accountQA.identityChanged=fn;},signOut:async()=>{if(window.__accountQA.signoutFailure)return {error:new Error('synthetic failure')};window.__accountQA.user=null;window.__accountQA.identityChanged('SIGNED_OUT',null);return {};}}};}` }));
  await page.route('**/api/**', async route => {
    const req = route.request(), url = { pathname: req.url().split('?')[0].replace(/^https?:\/\/[^/]+/, '') };
    requests.push({ path: url.pathname, method: req.method() });
    const q = await page.evaluate(() => ({ connected: __accountQA.connected, fail: __accountQA.fail, hold: __accountQA.hold, checks: __accountQA.checks }));
    if (q.hold) await page.waitForFunction(() => !__accountQA.hold);
    let result;
    if (url.pathname === '/api/providers/connection') {
      if (q.fail) return route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ error: 'Synthetic unavailable response' }) });
      if (req.method() !== 'GET') await page.evaluate(value => { __accountQA.connected = value; }, req.method() === 'POST');
      result = { connected: await page.evaluate(() => __accountQA.connected), model: 'claude-qa-model' };
    } else if (url.pathname === '/api/gen/credentials-ready') {
      check(JSON.stringify(req.postDataJSON()) === '{}', 'credential recovery sends no job ID or paid resume intent');
      if (await page.evaluate(() => __accountQA.recoveryFailure)) return route.fulfill({ status:503, contentType:'application/json', body:JSON.stringify({error:'Synthetic credential status unavailable'}) });
      result = { cleared: ['synthetic-waiting-job'], started: [] };
    } else if (url.pathname === '/api/setups/generate' && req.postDataJSON()?.action === 'check') {
      await page.evaluate(() => { __accountQA.checks++; });
      result = { connected: q.connected, ready: q.connected, enabled: true, model: 'claude-qa-model', issues: [] };
    } else throw new Error('Unexpected endpoint: ' + url.pathname);
    await route.fulfill({ contentType: 'application/json', body: JSON.stringify(result) });
  });
  await page.goto('http://127.0.0.1:4173/qa-workspace-account');
  await page.evaluate(async () => {
    const q = window.__accountQA = { user: { id: 'synthetic-owner', email: 'creator@example.test' }, connected: false, fail: false, hold: false, checks: 0, saves: 0, opened: 0 };
    localStorage.setItem('gametheory-api-key', 'synthetic-existing-tutor-key');
    const auth = await import('/js/auth.js?v=31'); await auth.initAuth(); q.auth = auth;
    const { createSetupCreation } = await import('/js/setup-create.js?v=8');
    const { createSetupGenerationClient } = await import('/js/setup-generation-client.js?v=7');
    const { setupDraft } = await import('/js/setup-model.js?v=4');
    const draft = setupDraft('Photography for beginners'); draft.brief.audience = 'New photographers';
    q.creation = createSetupCreation({ getUser: auth.getUser, client: createSetupGenerationClient(), sessions: { flush: async () => true, acknowledge: async () => true }, accountClient: { save: async () => { q.saves++; return { revision: 1 }; } }, navigate: () => {}, openJob: async () => { q.opened++; } });
    q.creation.render(document.querySelector('#content'), { id: 'setup-synthetic', owner: q.user.id, version: 1, draft });
  });
  await page.getByRole('heading', { name: 'Connect Claude to create your plan' }).waitFor();
  await page.getByRole('button', { name: 'Account', exact: true }).click();
  const modal = page.getByRole('dialog', { name: 'Your account' });
  await modal.getByLabel('Claude API key', { exact: true }).waitFor();
  const snapshot = await modal.ariaSnapshot();
  check(snapshot.includes('Claude · course creation') && !snapshot.includes('Model API keys'), 'real Account entry uses secure workspace modal');
  check(await page.locator('#auth-modal').count() === 0, 'legacy modal is not mounted in signed-in workspace');
  check(await modal.getByLabel('Claude API key', { exact: true }).getAttribute('type') === 'password', 'key is labelled and masked');
  check(await modal.getByRole('heading', { name: 'Your account', exact: true }).evaluate(el => el === document.activeElement), 'initial status does not open the mobile keyboard or steal title focus');
  check(await page.evaluate(() => __accountQA.saves === 1 && __accountQA.opened === 0), 'opening Account neither resaves setup nor starts a job');
  let focusContained = true;
  for (let i = 0; i < 12; i++) {
    await page.keyboard.press('Tab');
    focusContained &&= await page.evaluate(() => !document.hasFocus() || document.querySelector('dialog').contains(document.activeElement));
  }
  check(focusContained, 'Tab traversal stays in the modal or browser chrome, not background controls');
  await page.setViewportSize({ width: 1440, height: 1100 });
  await page.screenshot({ path: 'output/playwright/account-connection-2026-09-18/account-desktop.png' });
  const fits = () => modal.evaluate(el => { const r = el.getBoundingClientRect(); return r.left >= 0 && r.right <= innerWidth && el.scrollWidth <= el.clientWidth; });
  for (const width of [390, 320]) {
    await page.setViewportSize({ width, height: 844 }); check(await fits(), `Account fits ${width}px without horizontal scroll`);
    await modal.evaluate(el => { el.scrollTop = 0; });
    await page.screenshot({ path: `output/playwright/account-connection-2026-09-18/account-${width}.png` });
  }
  await modal.getByLabel('Claude API key', { exact: true }).fill('synthetic-new-key');
  await modal.getByRole('button', { name: 'Connect Claude', exact: true }).click();
  await modal.getByText('Claude connected securely. No course generation has started.', { exact: true }).waitFor();
  await page.waitForFunction(() => document.querySelector('.setup-create-provider h3')?.textContent === 'Claude is connected');
  check(await page.evaluate(() => document.querySelector('dialog').contains(document.activeElement)), 'background Create refresh does not steal modal focus');
  check(await page.evaluate(() => __accountQA.saves === 1 && __accountQA.opened === 0 && localStorage.getItem('gametheory-api-key') === 'synthetic-existing-tutor-key' && !JSON.stringify(localStorage).includes('synthetic-new-key')), 'connection preserves tutor key without browser persistence, setup resave or automatic job');
  await modal.getByRole('button', { name: 'Replace key', exact: true }).click();
  await modal.getByLabel('New Claude API key', { exact: true }).fill('synthetic-recovery-key');
  await page.evaluate(() => { __accountQA.recoveryFailure = true; });
  await modal.getByRole('button', { name: 'Replace connection', exact: true }).click();
  await modal.getByText('Claude is connected, but course status could not be refreshed. Check status to make Resume available. No course was restarted.', { exact:true }).waitFor();
  check(await modal.getByRole('button', { name:'Replace key',exact:true }).isVisible() && await modal.locator('input').count() === 0, 'credential status failure retains secure connection but not submitted key');
  await page.evaluate(() => { __accountQA.recoveryFailure = false; });
  await modal.getByRole('button', { name:'Check status',exact:true }).click();
  await modal.getByText('Connected securely', { exact:true }).waitFor();
  check(await modal.locator('[data-account-error]').count() === 0, 'clear-only credential recovery retries successfully without another key submission');
  await page.setViewportSize({ width: 390, height: 844 });
  await page.evaluate(() => { document.documentElement.dataset.theme = 'dark'; });
  await page.screenshot({ path: 'output/playwright/account-connection-2026-09-18/account-connected-dark-390.png' });
  await page.evaluate(() => { delete document.documentElement.dataset.theme; });
  await modal.getByRole('button', { name: 'Disconnect…', exact: true }).click();
  check(await modal.getByRole('button', { name: 'Keep connected', exact: true }).evaluate(el => el === document.activeElement), 'disconnect confirmation focuses the safe choice');
  const deletesBefore = requests.filter(r => r.method === 'DELETE').length;
  await modal.getByRole('button', { name: 'Keep connected', exact: true }).click();
  check(requests.filter(r => r.method === 'DELETE').length === deletesBefore, 'cancelled disconnect performs no mutation');
  await modal.getByRole('button', { name: 'Disconnect…', exact: true }).click();
  await page.screenshot({ path: 'output/playwright/account-connection-2026-09-18/account-disconnect-390.png' });
  await modal.getByRole('button', { name: 'Disconnect Claude', exact: true }).click();
  await modal.getByLabel('Claude API key', { exact: true }).waitFor();
  await page.waitForFunction(() => document.querySelector('.setup-create-provider h3')?.textContent === 'Connect Claude to create your plan');
  check(await page.getByRole('button', { name: 'Create course plan →', exact: true }).count() === 0, 'disconnect removes stale paid-start control');
  await page.evaluate(() => { __accountQA.fail = true; });
  await modal.getByLabel('Claude API key', { exact: true }).fill('synthetic-rejected-key');
  await modal.getByRole('button', { name: 'Connect Claude', exact: true }).click();
  await modal.getByRole('button', { name: 'Check status', exact: true }).waitFor();
  check(await modal.locator('[data-account-error]').evaluate(el => el === document.activeElement) && await modal.locator('input').count() === 0, 'uncertain save clears key, focuses error and requires status recheck');
  const errorContrast = () => modal.locator('[data-account-error]').evaluate(el => {
    const rgb = color => color.match(/[\d.]+/g).map(Number);
    const style = getComputedStyle(el), fg = rgb(style.color), overlay = rgb(style.backgroundColor), base = rgb(getComputedStyle(el.closest('dialog')).backgroundColor);
    const alpha = overlay[3] ?? 1, bg = overlay.slice(0,3).map((v,i) => v * alpha + base[i] * (1-alpha));
    const lum = c => c.slice(0,3).map(v => v/255).map(v => v <= .04045 ? v/12.92 : ((v+.055)/1.055)**2.4).reduce((sum,v,i) => sum + v * [.2126,.7152,.0722][i],0);
    const a = lum(fg), b = lum(bg); return (Math.max(a,b)+.05)/(Math.min(a,b)+.05);
  });
  check(await errorContrast() >= 4.5, 'light-mode error text meets normal-text contrast');
  await page.screenshot({ path: 'output/playwright/account-connection-2026-09-18/account-error-390.png' });
  await page.evaluate(() => { document.documentElement.dataset.theme = 'dark'; });
  check(await errorContrast() >= 4.5, 'dark-mode error text meets normal-text contrast');
  await page.screenshot({ path: 'output/playwright/account-connection-2026-09-18/account-error-dark-390.png' });
  await page.evaluate(() => { delete document.documentElement.dataset.theme; });
  await page.evaluate(() => { __accountQA.fail = false; __accountQA.connected = true; });
  await modal.getByRole('button', { name: 'Check status', exact: true }).click();
  await modal.getByRole('button', { name: 'Replace key', exact: true }).waitFor();
  await page.waitForFunction(() => document.querySelector('.setup-create-provider h3')?.textContent === 'Claude is connected');
  check(true, 'status recheck reconciles Create after an ambiguous mutation');
  await modal.getByRole('button', { name: 'Replace key', exact: true }).click();
  check(await modal.getByLabel('New Claude API key', { exact: true }).evaluate(el => el === document.activeElement), 'replace focuses new masked key');
  await modal.getByRole('button', { name: 'Cancel', exact: true }).click();
  await page.keyboard.press('Escape');
  check(await modal.count() === 0 && await page.getByRole('button', { name: 'Account', exact: true }).evaluate(el => el === document.activeElement), 'Escape closes Account and restores entry focus');
  const checksBefore = await page.evaluate(() => __accountQA.checks);
  await page.evaluate(() => { __accountQA.connected = true; __accountQA.hold = true; window.dispatchEvent(new CustomEvent('learnable-provider-connection-changed', { detail: { owner: __accountQA.user.id } })); });
  await page.getByRole('button', { name: 'Please wait…', exact: true }).waitFor();
  await page.evaluate(() => { __accountQA.connected = false; window.dispatchEvent(new CustomEvent('learnable-provider-connection-changed', { detail: { owner: __accountQA.user.id, connected: false } })); __accountQA.hold = false; });
  await page.getByRole('heading', { name: 'Connect Claude to create your plan' }).waitFor();
  check(await page.evaluate(before => __accountQA.checks >= before + 2 && __accountQA.saves === 1, checksBefore), 'connection change during an in-flight readiness check is queued without rewriting setup');
  await page.evaluate(() => { __accountQA.connected = true; });
  await page.getByRole('button', { name: 'Account', exact: true }).click();
  await modal.getByRole('button', { name: 'Replace key', exact: true }).waitFor();
  await modal.getByRole('button', { name: 'Replace key', exact: true }).click();
  await page.evaluate(() => { __accountQA.hold = true; });
  await modal.getByLabel('New Claude API key', { exact: true }).fill('synthetic-pending-key');
  await modal.getByRole('button', { name: 'Replace connection', exact: true }).click();
  check(await modal.getByRole('button', { name: 'Replace connection', exact: true }).isDisabled(), 'pending mutation disables duplicate submits');
  await modal.getByRole('button', { name: 'Close account', exact: true }).click();
  await page.evaluate(() => { __accountQA.hold = false; });
  await page.waitForFunction(() => document.querySelector('.setup-create-provider h3')?.textContent === 'Claude is connected');
  check(await modal.count() === 0, 'late response after dismissal does not reopen Account');
  await page.getByRole('button', { name: 'Account', exact: true }).click();
  await modal.getByRole('button', { name: 'Replace key', exact: true }).waitFor();
  await page.evaluate(() => { __accountQA.signoutFailure = true; });
  await modal.getByRole('button', { name: 'Sign out', exact: true }).click();
  await modal.getByText('Sign-out couldn’t be confirmed. Try again.', { exact: true }).waitFor();
  check(await page.evaluate(() => !!__accountQA.auth.getUser()), 'failed signout does not pretend account is signed out');
  await modal.getByRole('button', { name: 'Replace key', exact: true }).click();
  await page.evaluate(() => { __accountQA.hold = true; });
  await modal.getByLabel('New Claude API key', { exact: true }).fill('synthetic-other-owner-pending');
  await modal.getByRole('button', { name: 'Replace connection', exact: true }).click();
  await page.evaluate(() => { __accountQA.user = { id: 'other-synthetic-owner', email: 'other@example.test' }; __accountQA.identityChanged('SIGNED_IN', { user: __accountQA.user }); __accountQA.hold = false; });
  await modal.waitFor({ state: 'detached' });
  check(await page.evaluate(() => __accountQA.auth.getUser().id === 'other-synthetic-owner'), 'account switch dismisses old connection UI even with a request pending');
  await page.getByRole('button', { name: 'Account', exact: true }).click();
  await modal.getByRole('button', { name: 'Replace key', exact: true }).waitFor();
  check(await modal.getByText('other@example.test', { exact: true }).isVisible() && !await modal.getByText('creator@example.test', { exact: true }).count(), 'reopening shows only the current account');
  await page.evaluate(() => { __accountQA.signoutFailure = false; });
  await modal.getByRole('button', { name: 'Sign out', exact: true }).click();
  await modal.waitFor({ state: 'detached' });
  check(await page.evaluate(() => !__accountQA.auth.getUser()), 'successful signout clears identity and dialog');
  check(!requests.some(r => r.path === '/api/gen/start') && await page.evaluate(() => __accountQA.opened === 0), 'all connection operations are non-generative');
  check(errors.length === 0, 'no uncaught browser errors');
  return { checks, total: checks.length, requests, evidence: 'Real Account/Auth/client/Create modules + styles. Auth SDK and API responses synthetic; no real account, provider or email.' };
})
